### ISSUE TITLE
read proxy account registry from chain upon enclave startup

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#1]
Upon start up, the stateless enclave does not know of previously registered proxy accounts. Because the proxies are stored onchain with the proxy pallet, it would be reasonable to get the accounts from the chain when the enclave chain relay is first initialised. 

Suggested approach: Upon worker start up, the worker calls into the chain storage via the substrate-api-client (rpc interface) to get all registered proxy accounts. The enclave is called via ecall (e.g. init_proxy_register(...) and are stored in memory with an atomic pointer
(see https://github.com/scs/substraTEE-worker/blob/master/enclave/src/rpc/worker_api_direct.rs#L85-L107 for an atomic pointer handling example within the enclave)

When designing the enclave in memory storage the following interactions should be possible (maybe it makes sense to provide interface functions? Up to you):
* Check if the given AccountID (main) is registered
* Check if the given AccountID (proxy) and AccountID (main) are assosciated
* add and remove proxy account

**Comment by brenzi** [comment]
as all direct calls will provide the main account as an argument, I guess our proxy registry should be of the form:
```
map AccountId (main) -> Vec<AccountId (proxy)>
```
This way, we can lookup the beneficiary account and get ll permissioned proxies so we can check if the signer of the call is in the set.

**Comment by brenzi** [comment]
@ksr30 please check our [docs on accessing onchain storage](https://www.substratee.com/howto_access_onchain_storage.html)

There is also an example of a storage map in encointer you may want to look at:
https://github.com/encointer/encointer-worker/blob/3be977ba4d8de76ac724f69c7928e67f9dd375d3/stf/src/sgx.rs#L352

**Comment by jaxter03** [comment]
Thanks @haerdib @brenzi ... i will look into it

**Comment by brenzi** [comment]
open question:

* We can only get read proofs for single storage keys, not for an entire `storage_map`. This means we somehow need to know all the main accounts that have ever deposited using the ocex pallet. Then we could fetch proxies per main account with read proof

**Comment by Gauthamastro** [comment]
@brenzi , We can define three storage items on-chain

```rust
pub struct PolkadexLinkedAccount{
      prev: AccountID,
      next: Option<AccountID>,
      proxies: Vec<AccountID>

}

// Inside the on-chain ocex storage
// We define three storage as given below
decl_storage!{
...
     FirstAccount: T::AcountID
     LastAccount: T::AccountID
     pub mainAccounts get(fn get_main_accounts): map hasher(blake2_128_concat) T::AccountId => PolkadexLinkedAccount;
...
}
```

The first transaction that adds the registers the first account will set the storage of "FirstAccount" also and subsequent add_account calls will check if FirstAccount is set or not, if it is set, then we just read the struct stored corresponding to the "LastAccount" key from mainAccounts storage map and modify the PolkadexLinkedAccount's prev, proxies, and next fields.
Also we update "LastAccount" storage to the current accountID in question.

Thanks to @ksr30  for the linked list idea!

**Comment by Gauthamastro** [comment]
For the off-chain worker, it can read the "FirstAccount" storage's value and use that to continuously read all the remaining accounts using the next field of the PolkadexLinkedAccount.

**Comment by haerdib** [comment]
An example, where the enclave uses the read_proof with an ocall to the worker: 

The enclave calls into the worker to get onchain information (ocall wrapper): 
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L933
actual ocall:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L1070
in edl file:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/Enclave.edl#L116-L119
ocall on worker side:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/worker/src/main.rs#L744
in this function, the worker gets the storage by key, including the proof and returns both to the enclave.

The enclave verifies the proof: 
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L983

The StorageProof functions are defined in the chain relay: 
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/chain_relay/src/storage_proof.rs

**Comment by haerdib** [comment]
Issue: If we do an ocall from the enclave to get the account registry, we need to predefine the returned size of the linked list.

Solution proposal: After initialising chain relay, the worker knows of the latest header of the enclave and can get the state & storage proof at this header and do an ecall into the enclave which verifies the storage proof at the latest header.

| Possible vulnerability  | Mitigation     | 
| :------------- | :---------- | 
|  Worker tampers with account data |  storage proof  of linked list |
| Worker omits ecall init_account_registry   | enclave will return an error without an initialised registry when syncing with the chain|
|  Worker ecalls init_account_registry before initialising chain relay, no validator set | enclave fails unsealing a validator and returns an error |
|  Worker ecalls init_account_registry and afterwrads reinitialisises the chain relay. The worker includes a linked list of accounts with a matching storage proof. The enclave will deem the proof and the list correct and initialise the registry. Afterwards the worker inits the chain relay to a different genesis hash, resulting in a mismatch of the registered accounts and the actual chain | When initialising the chain relay, by default the enclave could remove the contents of the linked account registry. |

Have I missed anything?

**Comment by brenzi** [comment]
I wonder if we're overengineering here: As we have a single instance of the GW running, that instance will sync the chain from genesis and catch all proxy registrations from then on. Couldn't we just maintain proxies as we do with balances (where we sync all deposit/withdrwaw extrinsics besides direct invoc)?
