### ISSUE TITLE
update balance upon finalized `deposit` onchain extrinsic

### ISSUE THREAD

**Issue by brenzi** [Polkadex-Substrate/polkadexTEE-worker#10]
the enclave scans all new blocks from the chain-relay for relevant extrinsics. See:
https://github.com/scs/substraTEE-worker/blob/e2619abfff07a2fd9054fcbd4e23879cc0d0eba3/enclave/src/lib.rs#L778

We need to add a new extrinsic to that list and update the in-enclave-memory balance storage accordingly

depends on #3

**Comment by Gauthamastro** [comment]
merged in #52
