### ISSUE TITLE
Use fixed point decimal conversion for the OpenFinex API

### ISSUE THREAD

**Issue by murerfel** [Polkadex-Substrate/polkadexTEE-worker#102]
In order to have a clean conversion between decimals and block chain / substrate integers, we must use a conversion algorithm that does not involve any floating point numbers (as we do now). We need to parse the decimal directly from string.

According to OpenFinex, they use https://github.com/shopspring/decimal in Go.

Substrate has some support for this, see https://substrate.dev/rustdocs/v3.0.0/node_template_runtime/struct.Permill.html . It is not clear however how much of this can be used. Further investigation is needed.

**Comment by haerdib** [comment]
This might be the better link: https://docs.rs/sp-arithmetic/3.0.0/sp_arithmetic/index.html

As far as I understand [Fixed point U128](https://docs.rs/sp-arithmetic/3.0.0/sp_arithmetic/fixed_point/struct.FixedU128.html) does us not give alot of precision. So we probably need to work with [Perbill](https://docs.rs/sp-arithmetic/3.0.0/sp_arithmetic/per_things/struct.Perbill.html) and [Perquintill](https://docs.rs/sp-arithmetic/3.0.0/sp_arithmetic/per_things/struct.Perquintill.html) to get a higher precision.. 

But so far I've never worked with such per_things so I'm a bit at a loss here.

**Comment by murerfel** [comment]
The issue with https://docs.rs/sp-arithmetic/3.0.0/sp_arithmetic/index.html is that it's not arbitrary precision (like the OpenFinex Go counterpart), and a lot of useful features are in std. But it might still be our best bet, since I could not find any arbitrary precision fixed-point decimal library in Rust.

**Comment by murerfel** [comment]
As described in PR https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/125 , I ended up writing my own parser/serializer for fixed point decimals.
