### ISSUE TITLE
Parse OpenFinex's `marketid` in a generic way

### ISSUE THREAD

**Issue by murerfel** [Polkadex-Substrate/polkadexTEE-worker#105]
The way the `marketid` is constructed, is simply by concatenating the two involved currencies/asset types together to form this id. One example would be: `btcusd` for BitCoin->USD. Since there is no separator and not all assets have the same string length, it becomes impossible to uniquely identify the two asset types involved.

OpenFinex proposes to use their REST API to query the `marketid` and get back additional information that would allow us to construct our own `MarketId`: https://uat.opendax.app/api/v2/finex/public/markets 
This would however add a lot of new complexity to interface with OpenFinex, and would require us to have a REST Client inside the enclave to query this information.

@Gauthamastro is discussing alternatives with OpenWare

*Update*: OpenWare will add a WebSocket call to retrieve the markt id information

**Comment by Gauthamastro** [comment]
Openware will make market data available in ws

**Comment by haerdib** [comment]
I was not able to access the market data via ws. For me there are two options to proceed:
1) Ask openfinex if they have it already implemented, and if yes, then how we should actually call it. It does not seem obvious to me.
2) proceed with the HTTP GET command. This would require only little extra work in the current ws implementation. But it should definitely be replaced by a ws call when we start working with TLS.

@Gauthamastro , how should we proceed here?

**Comment by haerdib** [comment]
Alright, openfinex has updated its ws api:
Example request:
`[1, 1, "get_markets", []]`
Example response:
`[2,1,"get_markets",[{"id":"btcusd","name":"BTC/USD","base_unit":"btc","quote_unit":"usd","state":"enabled","amount_precision":4,"price_precision":4,"min_price":"0.0001","max_price":"0","min_amount":"0.0001","position":100,"filters":[]},{"id":"trsteth","name":"TRST/ETH","base_unit":"trst","quote_unit":"eth","state":"enabled","amount_precision":4,"price_precision":4,"min_price":"0.0001","max_price":"0","min_amount":"0.0001","position":105,"filters":[]}]]`
