### ISSUE TITLE
Fix tests in `test_polkadex_gateway.rs` concerning the order cache

### ISSUE THREAD

**Issue by murerfel** [Polkadex-Substrate/polkadexTEE-worker#106]
Because of some conflicts with the changing of the cache interface, I had to comment out some checks in the tests: 

https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/13ad6ce39b76b8fe2caef09a11896256105e5c39/enclave/src/test_polkadex_gateway.rs#L1797-L1812

Once the new cache is done, update these lines to propely use the new cache

**Comment by haerdib** [comment]
I think these unit tests 

https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/13ad6ce39b76b8fe2caef09a11896256105e5c39/enclave/src/test_polkadex_gateway.rs#L1818-L1836

are rendedered obsolete with PR #108
