### ISSUE TITLE
Removal of all warnings, incl. clippy

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#115]

**Comment by haerdib** [comment]
worker clippy warnings will be removed with PR #116

**Comment by arrudagates** [comment]
Should unused variables in function calls be removed or just prefixed with an underscore?

**Comment by haerdib** [comment]
Hm... it depends? :-)
I guess for now mark them with an underscore. It's faster and maybe there was a reason for adding this variable but it's just not implemented yet.
