### ISSUE TITLE
Write a HowTo Tutorial

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#124]
To run the success scenario of PolkaDEX, four instances need to be run:
1. Polkadex node
2. polkadex worker
3. openfinex server
4. user client

Eventually there should be a script starting all these processes without the user needing to do much, but currently this is not implemented. Therefore it would make sense to document a short HowTo so that everyone can start & test the code. 
Documentation can be written down here: https://github.com/Polkadex-Substrate/polkadex-docs/tree/master/docs

@Gauthamastro in which chapter would you like to have the HowTo, resp. the tutorial?

**Comment by Gauthamastro** [comment]
Let's create a doc9, with the HowTos information

**Comment by haerdib** [comment]
I've created two docs, one for [openfinex server](https://github.com/Polkadex-Substrate/polkadex-docs/blob/develop-KnowHow-dump/docs/doc9-tutorialsOpenfinexServer.md) and one for the [worker](https://github.com/Polkadex-Substrate/polkadex-docs/blob/develop-KnowHow-dump/docs/doc9-tutorialsWorker.md). None for the node yet, as this is just a start up for me, nothing special there from my side. 

The worker however I'm starting without a docker. @Gauthamastro  or @mullefel   maybe you'd want to dump some short docker how tos?

I'm leaving this issue open because eventually there will be a need for the final, non-developer tutorial.

**Comment by haerdib** [comment]
What's left to do:
1. @haerdib: Write all possible cli commands & their (optional) parameters
2. @ksr30: docker start up

**Comment by haerdib** [comment]
I added the cli commands to the [worker](https://github.com/Polkadex-Substrate/polkadex-docs/blob/develop-KnowHow-dump/docs/doc9-tutorialsWorker.md), removing myself from this issue.

**Comment by Gauthamastro** [comment]
This is blocked since docker is not working
