### ISSUE TITLE
implement demo bash script as end2end test

### ISSUE THREAD

**Issue by brenzi** [Polkadex-Substrate/polkadexTEE-worker#13]
demonstrate the following scenarios

Scenario 1: Happy flow
1.	Alice and Bob both create an account and receive funds from faucet (some native tokens as well as 200 tokenA for Alice and 200 tokenB for Bob)
2.	Alice and Bob both create and register a proxy account
3.	Alice deposits 100 tokenA 
4.	Bob deposits 100 tokenB
5.	Alice places a limit order selling 50 tokenA at a limit of 40 tokenB
6.	Bob places a limit order buying 50 tokenA at a limit of 60 tokenB
7.	The matching engine clears the match, sends it to the gateway
8.	The gateway settles the match, publishes all details
9.	The offchain balance of Alice is 50 tokenA plus 50 tokenB
10.	The offchain balance of Bob is 50 tokenA plus 50 tokenB
11.	Alice withdraws all her tokenB through direct call to gateway
12.	Bob withdraws all his tokenA through indirect extrinsic
13.	The offchain balance of Alice is zero tokenB and Bob is zero tokenA
14.	The onchain balance of Alice is 50 tokenB and Bob is 50 tokenA

Scenario 2: 
Along scenario 1 with the differences of:
•	Bob submits an order buying 50 tokenA at a limit of 110 tokenB
•	The order gets rejected by the gateway because it is not backed by Bobs balance

Scenario 3: 
Along scenario 1 with the differences of:
•	After the settled trade, Bob tries to withdraw 60 tokenB
•	The withdrawal gets rejected by the gateway because it is not backed by Bobs balance

Scenario 4:
Along scenario 1 with the differences of:
•	Matching engine returns a match involving an order that hasn’t been sent through the gateway
•	The match gets rejected by the gateway

**Comment by haerdib** [comment]
Might be worth to check out https://github.com/encointer/encointer-node/tree/ipfs-icon-upload/client and write the demo in python instead of bash script. 

Thanks @clangenb for the input.

**Comment by clangenb** [comment]
I would strongly recommend doing it with a python wrapper for the following reasons:
* Bash is too error-prone and tedious to debug. 
* stdout of processes is much easier to parse in python
* Allows better abstractions
