### ISSUE TITLE
Create new balance storage entry upon settle trade event

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#150]
Scenario:
- Alice deposits 100 btc to the enclave acc
- Bob deposits 100 usd to its encalve acc
- Alice and bob trade 50 btc and 50 usd
but Bob does not have a balance storage entry for btc nor does alice for usd, so https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/polkadex_balance_storage/balance_storage.rs#L184  throwns an error.

A new storage entry should be initialized instead:     https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/polkadex_balance_storage/balance_storage.rs#L51

**Comment by jaxter03** [comment]
Merged
