### ISSUE TITLE
Substrate-api-client only offeres balance pallet

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#157]
To submit extrsinics from the enclave to the node, we somehow need to ensure the enclave has some funds. But currently this is not possible

https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/main.rs#L709 does not transfer any balances because Polkadex node does not support balance pallet.

We should either
a) adapt https://github.com/Polkadex-Substrate/substrate-api-client/blob/master/src/extrinsic/balances.rs#L50
b) create an additional function (or even file) and adapt the worker
c) add the balance pallet to the Polkadex node

With asset ids only (option a) and b): Is there any main asset id that the enclave should pay in?

**Comment by haerdib** [comment]
@Gauthamastro @brenzi what is your opinion regarding this issue?

**Comment by brenzi** [comment]
@haerdib clearly (b)

api-client is designed to support any pallet, so we can just call polkadex custom stuff easily by just assembling the call directly without using the helpers. Therefore, the worker needs to be modified to replace the transfer call with a custom one. Check api-client examples for that

**Comment by Gauthamastro** [comment]
@brenzi @haerdib We don't need to do that, Polkadex uses Balances Pallet, as you can see here https://github.com/Polkadex-Substrate/Polkadex/blob/develop/runtime/src/lib.rs#L399

**Comment by haerdib** [comment]
Closing this issue then - the problem seems to lie somewhere else (see main issue #154 )
