### ISSUE TITLE
Easy node debugging 

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#160]
To test the node & its extrinsic, it would be great to have some test calls implemented.

Currently, we are calling the node via the [substrate-api-client](https://github.com/Polkadex-Substrate/substrate-api-client). Example of the [client](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/client/src/main.rs) calling the api: 
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/client/src/main.rs#L181-L208

Or from within the [worker](https://github.com/Polkadex-Substrate/polkadexTEE-worker/tree/develop/worker): https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/main.rs#L689-L719
(balance transfer function can be found here: https://github.com/Polkadex-Substrate/substrate-api-client/blob/master/src/extrinsic/balances.rs#L50-L57)

**Comment by haerdib** [comment]
The currently implemented demo script (calling deposit, withdraw and so on) can be found here:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/demo-script-squashed/client/demo_openfinex.py
 
respective the ocex pallet call implementations: 
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/demo-script-squashed/client/src/ocex_commands.rs

**Comment by haerdib** [comment]
@Gauthamastro  Can we close this issue ?

**Comment by Gauthamastro** [comment]
This issue is no longer required since we have integration tests with Openfinex with happy path working fine
