### ISSUE TITLE
polkadex parachain

### ISSUE THREAD

**Issue by howl111** [Polkadex-Substrate/polkadexTEE-worker#165]
Hi, w are blockchain team, an' we wanna build parachain with Polkadex nucle for your future auctions, 10 000 transaction or 100 000 transaction per sec for orderbook, how do we get around openfinex (not for free and we cant ...) and achieve these numbers? please help

**Comment by Gauthamastro** [comment]
Polkadex is not a project for building parachains. If you want to build parachain, you should be looking into this repo, https://github.com/paritytech/cumulus.

Closing this issue since it is not related to Polkadex, feel free to re-open if you have something Polkadex specific
