### ISSUE TITLE
get token balance storage does not work

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#168]
Currently, the token balance query to onchain is failing due to unknown reason:

- The [token-balance query](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/demo-script/client/src/main.rs#L272-L279) of a specific account is always returning None, no error is issued. So, the pallet is found, but something is wrong with the key.
- To test with a simpler storage query, I implemented the [TotalIssuance query](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/demo-script/client/src/main.rs#L281-L288) which also returns None.
- The substrate-api-client is correctly detecting the different hashers (`map for 'Tokens' 'Accounts' has hasher1 StorageHasher::Blake2_128Concat hasher2 StorageHasher::Twox64Concat`) so I guess this is also not the problem.
- The [query on the balance pallet](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/demo-script/client/src/main.rs#L290-L297) is working, leading me to the conclusion that AccountId should be correct as well.
- AssetId could be the problem, but I checked both worker and node and they seem to be taking the same assetId from the [polkadex primitives](https://github.com/Polkadex-Substrate/polkadex-primitives/blob/main/src/assets.rs)
- I cargo updated both node and worker, rerun them, but it still did not work

Link to the orml_token pallet: https://github.com/Polkadex-Substrate/open-runtime-module-library.git

 What have I overlooked?...

**Comment by brenzi** [comment]
It does seem the CurrencyId type is indeed AssetId from polkadex primitives:
https://github.com/Polkadex-Substrate/Polkadex/blob/fb4c8a473da44dfe92de271370bd2e873ea1fc92/runtime/src/lib.rs#L425

And the orml pallet seems to really refer to `Tokens`
https://github.com/Polkadex-Substrate/Polkadex/blob/fb4c8a473da44dfe92de271370bd2e873ea1fc92/runtime/src/lib.rs#L488

However, I'm not sure if the order of the hashers is correct:
https://github.com/Polkadex-Substrate/open-runtime-module-library/blob/a8a2a671113e6a6370f0f97d8bb420e86ca04e06/tokens/src/lib.rs#L243

maybe print metadata and check manually?

It seems AccountId and PolkadexAccountId are not the same? Why use two different types?
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/dbdd6cc21db5939c43a70fad5ac0d2273edb741f/client/src/main.rs#L67

query balances pallet works, which uses AccountId, not PolkadexAccountId

**Comment by brenzi** [comment]
sorry, didn't mean to close.

Does reading token balances with polkadot-js/apps work?

**Comment by brenzi** [comment]
I believe this is a bug in api-client. check this:
https://github.com/scs/substrate-api-client/blob/731a3a5c3a16ed3ce7f1f6b50593a2cdfd08a39f/src/node_metadata.rs#L638

twox64concat actually just returns twox64, without concatenating the raw value.

@haerdib I think you should be able to fix this by comparing to (fixed) sub_xt:
https://github.com/paritytech/substrate-subxt/blob/08a3e6574d38ed7908e163ac554b81b59e0b8a67/src/metadata.rs#L295-L301

**Comment by haerdib** [comment]
> It seems AccountId and PolkadexAccountId are not the same? Why use two different types?
> 
> https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/dbdd6cc21db5939c43a70fad5ac0d2273edb741f/client/src/main.rs#L67
> 
> query balances pallet works, which uses AccountId, not PolkadexAccountId

Both types are exactly the same - but I really really wanted to be sure that this was not the issue, hence the extra import.

**Comment by haerdib** [comment]
> 
> 
> I believe this is a bug in api-client. check this:
> https://github.com/scs/substrate-api-client/blob/731a3a5c3a16ed3ce7f1f6b50593a2cdfd08a39f/src/node_metadata.rs#L638
> 
> twox64concat actually just returns twox64, without concatenating the raw value.
> 
> @haerdib I think you should be able to fix this by comparing to (fixed) sub_xt:
> https://github.com/paritytech/substrate-subxt/blob/08a3e6574d38ed7908e163ac554b81b59e0b8a67/src/metadata.rs#L295-L301

On it. Thanks for looking into it!!

**Comment by haerdib** [comment]
Fixed with https://github.com/Polkadex-Substrate/substrate-api-client/commit/c048828ad971c35dee45b873448d3712fccf76ea
 & https://github.com/Polkadex-Substrate/substrate-api-client/commit/441fdda8e059fa874e409675be8b289b86ba03ca
