### ISSUE TITLE
Remove clippy warnings & check clippy warnings with PR

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#179]
There are new clippy warnings which should be removed. After solving this issue, new PRs should be checked if they bring in new clippy warnings. If they do, CI should throw warnings / errors.

**Comment by arrudagates** [comment]
There seems to be a lot more clippy warnings that went by unnoticed, I will address those.

**Comment by arrudagates** [comment]
Issue closed by merging #185 and #180
