### ISSUE TITLE
Benchmark Polkadex Orderbook

### ISSUE THREAD

**Issue by zktony** [Polkadex-Substrate/polkadexTEE-worker#181]
**Context**
Perform different types of load testing of Polkadex Orderbook under different scenarios and create a complete report containing multiple test conditions and outcomes.

 **Tool**
We can use Gatling to perform different types of performance tests on our JSON-RPC based Websockets. Related resource (https://gatling.io/docs/gatling/reference/current/http/websocket/)

**Scenarios**
- [x] Check response time when multiple orders are created.
- [x] Find throughput of Gateway, if multiple create order requests are send.

**Comment by zktony** [comment]
@Gauthamastro @haerdib If you have any scenarios which we should benchmark, please add them to Scenarios List.

**Comment by zktony** [comment]
Things left to be implemented :-
- [x] Run benchmark code with active Openfinex server.
- [x] Create report of remaining scenarios.

**Comment by pavankanteti** [comment]
Waiting for Openware to issue license

**Comment by pavankanteti** [comment]
@Gauthamastro to review
