### ISSUE TITLE
Load Inmemory Enclave state from disk storage

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/polkadexTEE-worker#204]

**Comment by haerdib** [comment]
Upon worker restart, the enclave inmemory needs to be updated to its latest state by reading from permantent disc storage (which has been updated by IPFS snapshot previously if appropriate).

This applies to both nonce and balance storage.

This is already implemented in the [orderbook mirror](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db.rs). Example:

- [read everything in db](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db.rs#L135-L149)
- [load storage at worker startup](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/main.rs#L563-L566) and enter the enclave
- [load to inmemory in enclave](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/lib.rs#L425-L446)

**Comment by arrudagates** [comment]
Closed by https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/249
