### ISSUE TITLE
Create a general db struct

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#208]
create a general db struct (key: `Vec<u8>` and data: `Vec<u8>` input as well a storage path as input), change already existing [polkadex mirror db](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db.rs) accordingly

**Comment by arrudagates** [comment]
Does this issue only emcompasses the general db struct itself or does it also involve writing the implementations for the storages (balance, accounts_nonce)? Also should it replace RocksDB and drop the OrderBook specific code already written in [polkadex_db.rs](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db.rs) ?

**Comment by haerdib** [comment]
This issue only involves the general db as well as adapting the order book mirror struct. Balances and acounts nonce are a separate issue.

**Comment by arrudagates** [comment]
One more question, where should the general db module be located? in `TEE-worker/worker/src`?

**Comment by haerdib** [comment]
I think a separate folder would make sense, because more storage files will be used. Something like `TEE-worker/worker/src/polkadex-db` or something?

**Comment by pavankanteti** [comment]
EOD 28/7/2021

**Comment by haerdib** [comment]
Linking issue: #46

**Comment by pavankanteti** [comment]
EOD 29/7/21
