### ISSUE TITLE
Introduce IPFS snapshotting functionality to the db storages

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#211]
introduce IPFS snapshotting functionality to the db storages (if it should be moved to the individual structs or if it can be implemented in general db struct should be evaluated in this issue. Write_ipfs() is already exising, does not need to be reimplemented)

**Comment by Gauthamastro** [comment]
Think about using Filecoin :)

**Comment by pavankanteti** [comment]
Preparing the data, creating the snapshot and deciding the snapshotting interval

**Comment by haerdib** [comment]
Linking issue  #177 for better documentation:

Local permanent storage needs to be regularly snapshotted and saved to IPFS node (and pinned !).

Quote from @brenzi in issue https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/173#issuecomment-873540057
> Regarding the state that needs snapshotting: We only need to restore things that can't be synced from the chain again
> The proxy set doesn't strictly need snapshotting but it won't hurt (debug only. just don't restore, because you would overwrite chain-synced state)
> 
> the orderbook mirror, the balances, need snapshotting. The order cache for the OpenFinex API maybe not because these would be in limbo anyway if the ws connection breaks

Additionally we also need to snapshot the account nonce storage.

Summarising, the following disc storages need to be snapshotted to IPFS:
- [orderbook mirror](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db.rs#L63)
- balance, implemented in issue #209
- account nonce, implemented in issue #210 

Checkout https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/ipfs.rs for ipfs interaction example

I see two IPFS snapshotting options: 
1. save local storage snapshot regularly in IPFS
2. send a snapshot to IPFS whenever a local disc storage write occurs.

**Comment by haerdib** [comment]
Linking research issue: #214

**Comment by haerdib** [comment]
Possible storage solutions:
-serde, TODO: check out
-https://github.com/capsule-corp-ternoa/sgx-keyvault/blob/develop/enclave/src/ternoa/nft_registry_storage_helper.rs#L34-L54

**Comment by haerdib** [comment]
Closed with #244
