### ISSUE TITLE
In which language should we implement Trading Bot Library

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/polkadexTEE-worker#216]
Python or JS or Rust or Cython or C++ or GO or Hybrid?

**Comment by haerdib** [comment]
Provide documentation such that others can decide on the preferable language

While researching one should also document the (external) libraries that should/could be used for trading bot implementaton for the specifc language. 

Take a look at: https://github.com/ccxt/ccxt/wiki/Requirements

**Comment by pavankanteti** [comment]
Python is the chosen language for the first release
