### ISSUE TITLE
Create IPFS Service

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/polkadexTEE-worker#224]
Setup one IPFS node running on our AWS machines which we can connect to as fixed starting point in the decentrailced IPFS network.

Clone and build
https://github.com/rs-ipfs/rust-ipfs is a good starting point.

A.C:
- Relay messages from single node in IPFS network

Reference: https://docs.ipfs.io/how-to/command-line-quick-start/#take-your-node-online

**Comment by simonsso** [comment]
@brenzi @haerdib given your investigations in this area could you explain what we need.

A IPFS to http gateway?  A mDns service?

**Comment by brenzi** [comment]
For encointer, we just deployed a public ipfs node (gateway). We used the [go-ipfs service](https://docs.ipfs.io/how-to/command-line-quick-start/)
Consider locking the firewall to only allow using the API from defined IPs

If you prefer calling the API directly out of the enclave, there is [functionality for this in our worker](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/ipfs.rs):

**Comment by brenzi** [comment]
I know subsocial has played around with ipfs clusters but were disappointed. I think the way to go for now is running "ipfs pinning" services. i.e. run a substrate offchain-worker with your node that tells your ipfs pinners what cid's to pin/mirror

**Comment by simonsso** [comment]
Done. See note in notion.
