### ISSUE TITLE
Worker deadlocks after receiving balance update

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#236]
After merge of #228, noting down @arrudagates findings:

> The whole initialization process works fine, the mirrors initialize and the thread starts, the receiver in the enclave works, it reaches that point, but the actual problem is in the sender, or at least in the send function for the balance here: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/gabriel-dbthread/enclave/src/polkadex_balance_storage/balance_storage.rs#L37-L43
> 
> Up to line 39 everything works fine, it loads the sender as it should but then the send() hangs, it never goes past it and it also doesnt return anything, so thats precisely where its hanging, I'll have to come back to that tomorrow but if you find something out send it here that I'll read in the morning.

**Comment by arrudagates** [comment]
Closed by #240
