### ISSUE TITLE
Upload IPFS CID to blockchain

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#241]
The cid returned from IPFS uploading should be stored within the blockchain. The function is implemented in the OCEX pallet in the node. 

To upload the CID, the following ocex call should be issued: `update_CID(origin, cid: CidHash)`

Check the command on the node side : https://github.com/Polkadex-Substrate/Polkadex/blob/develop/pallets/ocex/src/lib.rs#L218-L233

**Comment by haerdib** [comment]
General idea (copy pasted from https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/173#issuecomment-897396344)

> The idea is to send IPFS CIDs to OCEX pallet which will then picked up by off chain workers and pin those CIDs after verification.

The Ipfs cid is generated in the [`snapshot_to_ipfs` function](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/211/ipfs-snapshotting/worker/src/polkadex_db/ipfs_storage_handler.rs#L70), which itself is called in an endless [snapshot_loop](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/211/ipfs-snapshotting/worker/src/polkadex_db/mod.rs#L72). For each storage ([orderbook](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db/orderbook.rs), [balance](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db/balances.rs) and [nonce](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db/nonce.rs)) a cid will be uploaded in a specifc time interval (see [here](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/211/ipfs-snapshotting/worker/src/polkadex_db/mod.rs#L110))
 
This cid needs to be uploaded to the susbtrate node chain via the [ocex pallet](https://github.com/Polkadex-Substrate/Polkadex/tree/main/pallets/ocex).

Because the enclave needs to sign the extrinsic, the extrinsic needs to be created within the enclave, even though all cid handling is outside of the enclave for now. 
An example of an extrsinic creation within the enclave & sending it to the node via untrusted side & api-client:
- untrusted side queries current [nonce](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/main.rs#L345-L346) and ecalls into trusted side (enclave):
    - https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/main.rs#L348-L349
    - https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/enclave/api.rs#L445-L457
- on the trusted side the [extrsinic is created](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/attestation.rs#L643-L652). The [call](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/attestation.rs#L641) needs to be adapted to match the oxec pallet call (like [here](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/lib.rs#L1150)) and the [information inlcuded](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/attestation.rs#L645) must be changed to contain atleast the ipfs cid.
- after the trusted side has created the extrsinic, the untrusted side [sends it to the node via the substrate-api-client](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/main.rs#L360)

So far the general information. Some details have been left out, but before I'll dig into these, we'll need to figure out who sends what to the node.

**Comment by haerdib** [comment]
Linking Issue / Epic on the Polkadex node side: https://github.com/Polkadex-Substrate/Polkadex/issues/187

**Comment by simonsso** [comment]
Peer issue on node side https://github.com/Polkadex-Substrate/Polkadex/issues/298

**Comment by haerdib** [comment]
Ecall process (on example of `perform_ra`):
- Define an extern C function on the untrusted side: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/enclave/api.rs#L107-L117
- Call it via an unsafe wrapper in the rust code: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/enclave/api.rs#L445-L457
- Define the function in the .edl file: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/Enclave.edl#L75-L79
- Define an unsafe extern C function on the trusted side: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/attestation.rs#L608-L664

More information on the edl file part you can find here: https://software.intel.com/content/www/us/en/develop/articles/software-guard-extensions-tutorial-series-part-4.html (chapter _The Enclave Definition Language_)

**Comment by arrudagates** [comment]
Closed by #273
