### ISSUE TITLE
Remove Orderbook and nonce mirror from IPFS snapshot loop

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#253]
According to issue https://github.com/Polkadex-Substrate/Polkadex/issues/298 , only balance mirror will be snapshotted to IPFS. Hence, the other two (nonce & orderbook) need to be removed from this loop:

Remove the following lines:

https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db/mod.rs#L109-L112
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/worker/src/polkadex_db/mod.rs#L137-L140

**Comment by arrudagates** [comment]
Closed by https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/255
