### ISSUE TITLE
Upgrade to Substrate's Latest Tag

### ISSUE THREAD

**Issue by pavankanteti** [Polkadex-Substrate/polkadexTEE-worker#256]
For upgrading, we should consider to rebase on the integritee-master branch (which is already on substate v 4.0.0-dev)

Use cargo update with --precise 88c64e06471cc12aa9b25290f24d5566bcb5dd82 argument. to set substrate main to the correct Sha. it is based on master branch, and the sha we updated main and develop branch to

**Comment by haerdib** [comment]
Closing this issue should also solve #229

**Comment by haerdib** [comment]
The following libraries need an update:
- [x]  https://github.com/Polkadex-Substrate/substrate-api-client-test-node -> https://github.com/Polkadex-Substrate/substrate-api-client-test-node/pull/3
- [x]  https://github.com/Polkadex-Substrate/substrate-api-client  -> https://github.com/Polkadex-Substrate/substrate-api-client/pull/8
- [x] https://github.com/Polkadex-Substrate/sgx-runtime -> https://github.com/Polkadex-Substrate/sgx-runtime/pull/4
- [x] worker (blocked by https://github.com/Polkadex-Substrate/Polkadex/issues/371) -> https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/288

**Comment by haerdib** [comment]
@simonsso Should we merge the updated versions to master? Or keep them in a separate branch for now? (changes will be breaking)
For example : 
- https://github.com/Polkadex-Substrate/substrate-api-client-test-node/pull/2
- https://github.com/Polkadex-Substrate/sgx-runtime/pull/3
- ...

**Comment by pavankanteti** [comment]
https://github.com/Polkadex-Substrate/substrate/releases/tag/monthly-2021-09%2B1

**Comment by haerdib** [comment]
Chosen substrate commit: https://github.com/paritytech/substrate/commit/dd297887c653e344c566e976c050b01f7dea8eef

**Comment by haerdib** [comment]
Closing this with the merge of https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/288
