### ISSUE TITLE
revert untyping AccountId to slice

### ISSUE THREAD

**Issue by brenzi** [Polkadex-Substrate/polkadexTEE-worker#35]
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/1fd9e7b03a7b75d0adecfa8cc158d36cc556ef19/polkadex-primitives/src/lib.rs#L12

@haerdib @ksr30 

Please use `AccountId32`, not `[u8; 32]`. I see trouble down the road and I think strong typing is a good thing, we shouldn't allow such workarounds.

If you need to insert it into a hash table, you just add `.encode()` if the main type doesn't implement the necessary trait.

**Comment by jaxter03** [comment]
Thanks, @brenzi ... I will do that

**Comment by Gauthamastro** [comment]
We can move the AccountId definition to polkadex-primitives ( the one in Polkadex Node repo) and import that pallet in enclave and worker for getting AccountId

cc: @haerdib @ksr30
