### ISSUE TITLE
implement balances snapshotting (write only)

### ISSUE THREAD

**Issue by brenzi** [Polkadex-Substrate/polkadexTEE-worker#4]
time interval based snapshotting of entire balances storage

no confidentiality requirements: store as plaintext

TBD: commit to IPFS or write to disk?

commit snapshots to chain with an `ocex::snapshot` extrinsic signed by enclave signing key

the task of recovering balances from a snapshot is out of scope but shall allow authentication. Therefore, the snapshot must be signed by the enclave.

**Comment by haerdib** [comment]
According to Gautham storage to disk is enough for the SoW . IPFS snapshots will be done in the next phase.

**Comment by haerdib** [comment]
Closing this as duplicate of #173
