### ISSUE TITLE
Configurability Sidechain logic

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/polkadexTEE-worker#40]
I don't like downgrades. I prefer configurability (should be implemented upstream)
Why not just introduce a CLI flag '--sidechain'. if present, produce blocks at a sidechain's fixed block interval. If absent, produce one block per onchain block, event-triggered

maybe, we should even do '--sidechain <specfile.json>', where specfile gives us the genesis state plus block interval info

_Originally posted by @brenzi in https://github.com/Polkadex-Substrate/polkadexTEE-worker/issues/16#issuecomment-839682133_

**Comment by haerdib** [comment]
I think this issue should be solved upstream, not here (https://github.com/integritee-network/worker/issues/247). So I suggest to close this issue.
@Gauthamastro @brenzi  can you live with this?

**Comment by Gauthamastro** [comment]
Yes
