### ISSUE TITLE
Independent Test Cases for Orderbook Mirror DB

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/polkadexTEE-worker#46]
Ideally, each unit test can be run independent of the other tests. Can the DB not be initialized twice?

_Originally posted by @haerdib in https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/43#discussion_r632552410_

**Comment by haerdib** [comment]
The previous initialisation of something seems to be an ongoing cargo test issue:
https://github.com/rust-lang/rfcs/issues/1664

We could use choose to run a single testing thread (https://doc.rust-lang.org/cargo/commands/cargo-test.html) so the test order is guaranteed. Though I'm not sure how much this will slow down the tests..

**Comment by Gauthamastro** [comment]
> The previous initialisation of something seems to be an ongoing cargo test issue:
> [rust-lang/rfcs#1664](https://github.com/rust-lang/rfcs/issues/1664)
> 
> We could use choose to run a single testing thread (https://doc.rust-lang.org/cargo/commands/cargo-test.html), so the test order is guaranteed. Though I'm not sure how much this will slow down the tests..

Yes, this looks like a good idea.

**Comment by pavankanteti** [comment]
Link to #208

**Comment by pavankanteti** [comment]
@arrudagates has already created the unit test. Hence closing this issue. 

Linking PR: https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/215
