### ISSUE TITLE
implement orderbook mirror

### ISSUE THREAD

**Issue by brenzi** [Polkadex-Substrate/polkadexTEE-worker#6]
The orderbook mirror remembers and tracks all orders in order to verify matches coming back from OpenFinex.

Design the orderbook mirror DB that allows to
* add order (upon RPC call)
* mutate order (upon `order` event from OpenFinex )
* remove order (upon event from OpenFinex or `cancel_order` RPC call)

the DB must be persisted across restarts of the worker but should be kept in-memory (enclave).

DB can be stored in plaintext but only the enclave may perform mutations -> DB must be signed such that the enclave can authenticate its contents upon startup

Writing to the DB must be asynchronous and may not block the trading activity or cause any latency.
 (possibly ocall spawning asynchronous write to disk)
Implement an interface that allows easy storage and removal of an order: sign the file & ocalls into the worker to store the file there.

the enclave thread listening to OpenFinex matches must be able to read the in-memory DB to verify matches with minimal latency

**Comment by haerdib** [comment]
Upon enclave start up, the permanent DB storage is read by the worker forwarded to the enclave, which stores it in an atomic pointer (ensuring thread safety).

**Comment by haerdib** [comment]
An example of the enclave signing something can be found for the block struct:

1. The keypair is first [unsealed](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L678)
2. The enclaves signs the block with a [.sign(signer_keypair) function](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/enclave/src/lib.rs#L711). 
3. The signing function is defined in the [Block struct](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/substratee-worker-primitives/src/block.rs#L144-L150)
4. The signature verification is defined in the [SignedBlock struct](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/master/substratee-worker-primitives/src/block.rs#L163-L170)
