### ISSUE TITLE
implement a valid nonce in the client calls

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#61]
replace the currently implemented dummy nonce (hardcoded 0) in the client call (trusted operation). This will mitigate the threat of replay attacks.
In a first step, a nonce storage needs to be implemented within the enclave.  Each account has its own assosciated nonce. Maybe the already implemented Balance stroage could be upgraded?  The client needs to be able to retrieve the nonce from the enclave. An example scenario could look like the following:

1. The client gets its assosciated nonce from the enclave via rpc call
2. The client signs the trusted operation with the received nonce & sends it to the enclave
3. The enclave compares the received nonce with the expected nonce
4. If the nonce is valid, the enclave will increment the stored nonce by one

**Comment by arrudagates** [comment]
@haerdib From what i understand, the nonce should be a hash including the account id + the number to be incremented, right? Or should it just be the number without hashing?
So the idea is to implement a field in the balance storage and functions to generate and compare the nonce?

**Comment by haerdib** [comment]
The nonce in general is just a number which is incremented with every call. This is used to prevent replay attacks - a signed message can not be faked, but an attacker could just send the same message again and it would be accepted. Hence, with every call there will be a nonce included, which will be validated. If the nonce of the call does not match the expected one, the request will be rejected.

So the enclave needs to somehow store the nonce it expects. In the sequence I've written above the client needs to request the nocne before every request call, but in a second step, the client could store its nonce locally and only request when necessary.

Because we are already storing the registered accounts, it would probably make sense to store the assosciated nonce there as well. I'm not sure if this should be implemented within the balance storage because there the tokenid is used for key generation. 
Take a look at the account registry, which is implemented here: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/polkadex.rs

**Comment by haerdib** [comment]
In the substraTEE-worker we have implemented something similar. As a reference you can take a look there:

1. Client requests nonce: https://github.com/scs/substraTEE-worker/blob/master/stf/src/cli.rs#L165-L180
2. stf reads trusted getter and finds that requester is looking for its nonce: https://github.com/scs/substraTEE-worker/blob/master/stf/src/sgx.rs#L340-L348
3. stf gets the accout nonce from its state: https://github.com/scs/substraTEE-worker/blob/master/stf/src/sgx.rs#L285-L294
4. nonce validation: https://github.com/scs/substraTEE-worker/blob/master/stf/src/sgx.rs#L469-L477

In your case there is no stf interaction, so you have to implement it somewhat differently. Take a look at the get_balance call, maybe you could do something along that way:
https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/stf/src/commands/get_balance.rs

Also, see this file: https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/stf/src/cli_utils/common_operations.rs
There seems to be already something prepared. I've not looked into detail there yet, but it might help.

**Comment by arrudagates** [comment]
I was trying to implement the function that was commented out in https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/stf/src/cli_utils/common_operations.rs but it didn't seem to change anything regardless of what i returned in it, is that the right path or should i be looking in another place?

**Comment by pavankanteti** [comment]
To close by 27/7/2021 @arrudagates

**Comment by pavankanteti** [comment]
@haerdib to review

**Comment by arrudagates** [comment]
Closed by PR #166
