### ISSUE TITLE
Minor comment: In case the main account is not registered but a proxy is given, this function will return an Error `ProxyNotRegisteredForMainAccount`. With the implemented error values, I'd expect an `MainAccountNotRegistered` error in this case

### ISSUE THREAD

**Issue by Gauthamastro** [Polkadex-Substrate/polkadexTEE-worker#67]
Minor comment: In case the main account is not registered but a proxy is given, this function will return an Error `ProxyNotRegisteredForMainAccount`. With the implemented error values, I'd expect an `MainAccountNotRegistered` error in this case

_Originally posted by @haerdib in https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/56#discussion_r638519265_

**Comment by arrudagates** [comment]
Closed by PR #166
