### ISSUE TITLE
It is possible to register the same account twice - or at least no error message is returned to client

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#80]
Not sure if this is the right place for this issue, but for now I'm opening it here because the client is implemented in the worker.

From the client I sent the same [unchecked extrinsic](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/ocex-client-calls/client/src/ocex_commands.rs#L55-L59) twice, and the node seemed to accepted them:

:~/polkadex/polkadexTEE-worker$ bin/substratee-client -p 9994 -P 2094 register-account //Bob
[+] Successfully registered new account 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty. Hash: 0xf9bb9ec6a3d57d4a3eeb00138ebbebccf7b4a326d77929500d9b205af1687dd4

:~/polkadex/polkadexTEE-worker$ bin/substratee-client -p 9994 -P 2094 register-account //Bob
[+] Successfully registered new account 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty. Hash: 0x46c29d561e20ecef527a2b327c7cf75a39a1148d2b692d54de2bd19f3f113653

The same happens when registering a proxy-account to a not yet registered main account. (or atleast the enclave does not accept the main account as registered.)

Is this an expected behaviour or is this a bug?
@Gauthamastro

**Comment by Gauthamastro** [comment]
I am not sure why it's happening. The pallet already handles these issues. Are you on the same commit version as Polkadex's develop branch? 

[ProxyAccount Checks](https://github.com/Polkadex-Substrate/Polkadex/blob/develop/pallets/ocex/src/lib.rs#L190)
[MainAccount Registration check](https://github.com/Polkadex-Substrate/Polkadex/blob/develop/pallets/ocex/src/lib.rs#L179)

**Comment by Gauthamastro** [comment]
I believe the client code might not be handling the events emitted. As you can see [here](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/ocex-client-calls/client/src/ocex_commands.rs#L66), the transaction is indeed finalized even if the execution results in emitting an error, but the error is generated as an event.

**Comment by haerdib** [comment]
I see - so the errors occuring within the pallet are not supposed to be returned as error to the client. Then, I will close this issue.
