### ISSUE TITLE
Error in polkadex_balance_storage: Pointer is Null

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#81]
When calling place_order from the RPC Interface 
(command: `bin/substratee-client -p 9994 -P 2094 trusted place_order --accountid=//Bob --proxyaccountid=//AliceIcognito --marketbase=polkadex --marketquote=dot --markettype=trusted --ordertype=limit --price=100 --orderside=ask --quantity=987345 --mrenclave=DUwXxgMPXqhXtyQaSe3U5LF8ECFwNM6ug182LecDJRzY  --direct` )
The error `Pointer is Null` in [polkadex_balance_storage](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/ocex-client-calls/enclave/src/polkadex_balance_storage.rs#L150) is occurring.

Both Bob and AliceIcognito  are registered, but none has ever withdrawn or deposited any funds. So I'd expect an "Insufficent Funds" or something like that, but not a Null Pointer.

@ksr30 @Gauthamastro am I missing something? Is there a need to manually add some funds to the balance storage before accessing it?

**Comment by jaxter03** [comment]
Hey @haerdib, To resolve this issue we have to call [this](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/ocex-client-calls/enclave/src/polkadex_balance_storage.rs#L138) at [here](https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/ocex-client-calls/enclave/src/lib.rs#L311). And one more thing @haerdib we have to first transfer fund from onchain to offchain worker before we can test place order.
