### ISSUE TITLE
Mock the calls to OpenFinex API in polkadex gateway to allow clean unit testing

### ISSUE THREAD

**Issue by murerfel** [Polkadex-Substrate/polkadexTEE-worker#85]
The polkadex gateway needs an interface to the OpenFinex API that allows it to be mocked for unit testing. This might require to put the polkadex gateway functions in a struct itself, that holds an OpenFinex API trait object.

The current state means, we cannot have passing unit tests and 'real' calls into OpenFinex at the same time, which is sub-optimal to say the least.

**Comment by haerdib** [comment]
closed by #118
