### ISSUE TITLE
docker setup for demo

### ISSUE THREAD

**Issue by brenzi** [Polkadex-Substrate/polkadexTEE-worker#9]
setup a docker demo with
* polkadexTEE-node
* polkadexTEE-worker
* OpenFinex
* a client (demo bash script)

**Comment by Gauthamastro** [comment]
The sequence of startup should be 
1. Polkadex Node
2. Openfinex
3. Polkadex-worker
4. Client

**Comment by Gauthamastro** [comment]
Finally, we found that docker is not working.
