### ISSUE TITLE
Error handling in balance storage

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#93]
Better error handling is required in polkadex_balance_storage.

 For now, I'm creating new balance entries whenever there's a deposit call and no entry exists for the asset and account id (https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/feature/fm-bh-openfinex-api/enclave/src/polkadex_balance_storage.rs#L114). But we should also discuss if `set_reserve_balance` or `set_free_balance` should create a new entry instead of issuing an error..

_Originally posted by @haerdib in https://github.com/Polkadex-Substrate/polkadexTEE-worker/pull/73#discussion_r649086106_

**Comment by haerdib** [comment]
Maybe it would make sense to wrap the whole balance storage in its own trait/struct to be able to mock the storage for the unit tests in the gatway.

**Comment by haerdib** [comment]
@Gauthamastro what are your thoughts on new balance storage entry creation : should a `set_reserve_balance ` resp. a `set_free_balance ` be able to create a new entry instead of throwing an error?

**Comment by Gauthamastro** [comment]
We have to initialize the balane with 0 for both `set_reserve_balance `  and `set_free_balance`

**Comment by Gauthamastro** [comment]
@haerdib @arrudagates It would be great to include the task of converting balance storage to a module in this issue.

**Comment by haerdib** [comment]
A module would be what exactly for you? Something like the order chaches? (https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/polkadex_cache/cancel_order_cache.rs#L29-L34)

**Comment by arrudagates** [comment]
> We have to initialize the balane with 0 for both `set_reserve_balance ` and `set_free_balance`

https://github.com/Polkadex-Substrate/polkadexTEE-worker/blob/develop/enclave/src/polkadex_balance_storage.rs#L110-L130

In the current version it is being initialized directly with the value being deposited, should it instead be initialized with 0 on both free and reserved and then add in the deposited amount?

**Comment by haerdib** [comment]
I think it would be cleaner to implement a seperate initialize function which always starts with 0 reserved and free.

In the current version I tried to avoid huge changes (due to rebase problems - there was a lot of parallel work ongoing at that time) and my aim was to test the openfinex api, not to clean up the balance storage.

**Comment by arrudagates** [comment]
Ok, the idea for the deposit function if theres no previous entry is to initialize as 0 and then retry the deposit?

**Comment by haerdib** [comment]
Hm.. this would mean the `get_mut` is called twice. Assuming there will be alooot of accounts & tokenids, this will consume some non neglectable amount of time.. which we should avoid I guess. We could use [`try_insert`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.try_insert) which returns a mutable reference to the value and modify it afterwards. Or ofc just direclty insert the given value like it is done now.

@Gauthamastro what are your thoughts on this?

**Comment by arrudagates** [comment]
I'm still trying to wrap my head around the codebase, but is it possible to pre-initialize every asset for an account?

**Comment by haerdib** [comment]
What would be the benefit to pre-initialize this? Not every user will use / trade in all types of assets, so you'd create an overhead of storage entries.

**Comment by arrudagates** [comment]
I guess so, i was just wondering if the overhead in storage could justify saving the overhead in time later, since there would be no need to check if the balance is initialized on every deposit. But yeah it's between using try_insert and just using the current solution.
