### ISSUE TITLE
Implement withdraw function being sent to openfinex

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#98]
For each accepted withdraw function, a withdraw call also needs to be sent to openfinex.

**Comment by haerdib** [comment]
This should be obsolete now, what do you think @Gauthamastro ?

**Comment by Gauthamastro** [comment]
No, we still need it since OpenFinex needs to keep track of it only then the frontend APIs can fetch it

**Comment by pavankanteti** [comment]
Openfinex doesn't need to be updated about funds.
