### ISSUE TITLE
Implement deposit function sent to openfinex

### ISSUE THREAD

**Issue by haerdib** [Polkadex-Substrate/polkadexTEE-worker#99]
For each accepted deposit call, a deposit call also needs to be sent to openfinex.

**Comment by haerdib** [comment]
This should be obsolete now, what do you think @Gauthamastro ?

**Comment by Gauthamastro** [comment]
Same as withdrawal we need it for frontend APIs

**Comment by pavankanteti** [comment]
Extend the Getbalance web socket stream to provide Deposit and Withdraw information

**Comment by pavankanteti** [comment]
Openfinex doesn't need to be updated about funds.
